[package]
name = "sand-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.*", features = ["dynamic_linking"] }
# bevy = "0.13.*" # for release do not use dynamic linking
rand = "0.8.*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
